{{- if .Values.separ.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "separ.fullname" . }}
  labels:
    {{- include "separ.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.separ.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "separ.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.spicedb.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spicedb
  labels:
    app: spicedb
spec:
  minAvailable: {{ .Values.spicedb.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: spicedb
{{- end }}
