{{- if or (not .Values.spicedb.secrets.existingPresharedKeySecret) (not .Values.separ.secrets.existingJwtSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "separ.fullname" . }}-secrets
  labels:
    {{- include "separ.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "separ.postgresqlUrl" . | quote }}
  {{- end }}
  {{- if .Values.externalSpicedbDatabase }}
  spicedb-database-url: "postgres://{{ .Values.externalSpicedbDatabase.username }}@{{ .Values.externalSpicedbDatabase.host }}:{{ .Values.externalSpicedbDatabase.port | default 5432 }}/{{ .Values.externalSpicedbDatabase.database }}?sslmode={{ .Values.externalSpicedbDatabase.sslMode | default "require" }}"
  {{- else if .Values.postgresql.enabled }}
  spicedb-database-url: {{ include "separ.spicedbPostgresqlUrl" . | quote }}
  {{- end }}
  {{- if not .Values.spicedb.secrets.existingPresharedKeySecret }}
  spicedb-preshared-key: {{ .Values.spicedb.secrets.presharedKey | quote }}
  {{- end }}
  {{- if not .Values.separ.secrets.existingJwtSecret }}
  jwt-secret: {{ .Values.separ.secrets.jwtSecret | quote }}
  {{- end }}
{{- end }}
