apiVersion: v1
kind: Service
metadata:
  name: {{ include "separ.fullname" . }}
  labels:
    {{- include "separ.labels" . | nindent 4 }}
spec:
  type: {{ .Values.separ.service.type }}
  ports:
    - port: {{ .Values.separ.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "separ.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

