{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "separ.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "separ.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.azureKeyVault.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureKeyVault.userAssignedIdentityClientId | quote }}
  {{- end }}
{{- end }}

